### ISSUE TITLE
Setting up playwright to monitor price

### ISSUE THREAD

**Issue by juliazlx** [junwenzh/price-monitor#17]
Playwright to monitor price that a user is tracking at regular intervals

**Comment by junwenzh** [comment]
Create a route that uses an url and selector to get the price using playwright.

**Comment by junwenzh** [comment]
Created an api route to get the price given a url and selector.

Next:

Add error handling. If the server fails to get the price, send a notification to the user. Stop the server from checking this website.

**Comment by junwenzh** [comment]
Partially done.

Created the skeleton to iterate through an array of urls then get the price through playwright.

Todo:

- [ ] Refactor the getPrice function because it's duplicated code used in the playwright controller
- [ ] Add functionality to use fetch instead of playwright
- [ ] Handle updating the db when a url/selector fails
- [ ] Update the db when we get results
- [ ] Add function to query for the urls from the database
- [ ] Add function to email users
- [ ] Set up PM2 to invoke the refresh route
